nosana:
  description: Run Test 2


global:
  image: registry.hub.docker.com/library/node:16

  trigger:
    branch:
      - all

jobs:
  - name: install-deps and run test
    commands: 
      - echo answer is $PATH path
      - npm ci
      - npm run test
    artifacts:
      - name: node_modules
        paths:
          - ./node_modules
  - name: test
    commands: 
      - ls node_modules
    resources:
      - name: node_modules
         