nosana:
  description: Run Test 2


global:
  image: registry.hub.docker.com/library/node:16
  environment:
    SECRET: 
      type: nosana-node/secret
      value: answer-to-life
  trigger:
    branch:
      - all

jobs:
  - name: install-deps and run test
    commands: 
      - sh -c 'answer is $SECRET'
      - npm ci
      - npm run test