nosana:
  description: Run Test 2

global:
  image: node:16
  trigger:
    branch:
      - all

jobs:
  - name: node failure
    commands: 
      - echo start (sleep 20)
      - sleep 20
      - echo end
    image: alpine
         